/* 화면 문구 (한국어·영어)와 배경 장소 이름 영어판. 이야기 문장은 js/data/i18n/en/<동물>.js */
registerUiText('ko', {
  'lang.switch': 'English ver.',
  'title.kicker': '도시의 바닥,',
  'title.main': '누구로 살아볼래?',
  'home.hint': '끝까지 살아남으면 기억 카드를 볼 수 있어요!',
  'home.bornBtn': '태어나기',
  'wall.open': '방명록 모아보기 ▼',
  'wall.close': '방명록 접기 ▲',
  'support.toggle': '제작자 응원하기',
  'album.toggle': '수집한 기억카드 보기',
  'album.title': '수집한 기억카드',
  'album.empty': '아직 모은 기억카드가 없어요.<br>끝까지 살아남으면 한 장씩 모여요.',
  'album.cardLabel': '{name} 기억카드 크게 보기',
  'direct.toggle': '캐릭터 직접 고르기',
  'close': '닫기 ✕',
  'memory.fail': '그림을 불러오지 못했어요.',
  'memory.dialog': '따뜻했던 기억',
  'memory.again': '기억 다시 보기',
  'memory.alt': '{name}의 따뜻했던 기억',
  'hud.hp': '체력',
  'hud.food': '포만',
  'birth.place': '{place}에서',
  'birth.title': '{name}로 태어났다',
  'birth.go': '살아 보기',
  'caption.age': '생후 {age} · {season}',
  'caption.night': ' · 밤',
  'next': '계속',
  'outcome.default': '시간이 흘렀다.',
  'error.title': '이 장면에서 문제가 생겼다',
  'error.body': '시나리오 데이터를 확인해 주세요.',
  'error.back': '처음으로',
  'ending.meta': '생후 {age} · {cause}',
  'ending.kids': ' · 남긴 {unit} {n}',
  'ending.again': '{name}로 다시',
  'ending.other': '다른 동물 고르기',
  'stamp.hp': '체력',
  'stamp.food': '포만',
  'stamp.starving': '굶주림',
  'tracker.me': '나',
  'note.survived': '{age} 생존',
  'note.placeholder': '{n}자까지 짧게',
  'note.title': '{name}에게 한 마디',
  'note.send': '남기기',
  'note.toWall': '방명록 보러가기 →',
  'note.emptyFor': '아직 {name}에게 남긴 말이 없어요. 첫 마디를 남겨 주세요.',
  'note.loadFail': '방명록을 불러오지 못했어요. 잠시 뒤에 다시 열어 주세요.',
  'note.cooldown': '조금 뒤에 다시 남길 수 있어요.',
  'note.sending': '남기는 중…',
  'note.sent': '남겼어요.',
  'note.sendFail': '남기지 못했어요. 잠시 뒤에 다시 시도해 주세요.',
  'note.empty': '한 마디를 적어 주세요.',
  'note.long': '{n}자까지 쓸 수 있어요.',
  'wall.to': '{name}에게',
  'wall.loading': '불러오는 중…',
  'wall.all': '전체',
  'wall.soon': '방명록은 곧 열려요.',
  'wall.none': '아직 남긴 말이 없어요. 한 번 살아 보고 첫 마디를 남겨 주세요.',
  'support.kakaopay': '라떼 한 잔 보내기',
  'support.toss': '토스로 응원하기',
  'support.qrAlt': '카카오페이 송금 QR 코드',
  'support.linkedin': '제작자 링크드인',
  'support.intro': '세상이 혼란스럽고 저는 내일을 모르겠습니다. 그래도 이것저것을 만드는 디자이너입니다. 참고로 아이스 라떼를 몹시 좋아합니다.',
});

registerUiText('en', {
  'lang.switch': '한국어',
  'title.kicker': 'Down on the city floor,',
  'title.main': 'who will you be?',
  'home.hint': 'Make it to the end to unlock a memory card!',
  'home.bornBtn': 'Be born',
  'wall.open': 'Guestbook ▼',
  'wall.close': 'Close guestbook ▲',
  'support.toggle': 'Support the maker',
  'album.toggle': 'My memory cards',
  'album.title': 'Memory cards',
  'album.empty': 'No memory cards yet.<br>Make it to the end to collect one.',
  'album.cardLabel': 'Open the {name} memory card',
  'direct.toggle': 'Pick an animal',
  'close': 'Close ✕',
  'memory.fail': 'Couldn’t load the picture.',
  'memory.dialog': 'A warm memory',
  'memory.again': 'See the memory again',
  'memory.alt': 'A warm memory of the {name}',
  'hud.hp': 'Health',
  'hud.food': 'Food',
  'birth.place': 'at {place}',
  'birth.title': 'Born a {name}',
  'birth.go': 'Live it',
  'caption.age': '{age} old · {season}',
  'caption.night': ' · night',
  'next': 'Next',
  'outcome.default': 'Time passed.',
  'error.title': 'Something went wrong here',
  'error.body': 'Please check the story data.',
  'error.back': 'Back to start',
  'ending.meta': '{age} old · {cause}',
  'ending.kids': ' · left behind {n} {unit}',
  'ending.again': 'Again as a {name}',
  'ending.other': 'Pick another animal',
  'stamp.hp': 'Health',
  'stamp.food': 'Food',
  'stamp.starving': 'Starving',
  'tracker.me': 'me',
  'note.survived': 'lived {age}',
  'note.placeholder': 'Keep it short ({n} max)',
  'note.title': 'A word for the {name}',
  'note.send': 'Leave',
  'note.toWall': 'See the guestbook →',
  'note.emptyFor': 'No one has left a word for the {name} yet. Be the first.',
  'note.loadFail': 'Couldn’t load the guestbook. Try again in a bit.',
  'note.cooldown': 'You can leave another one in a moment.',
  'note.sending': 'Leaving…',
  'note.sent': 'Left!',
  'note.sendFail': 'Couldn’t leave it. Try again in a bit.',
  'note.empty': 'Write a word first.',
  'note.long': 'Up to {n} characters.',
  'wall.to': 'to the {name}',
  'wall.loading': 'Loading…',
  'wall.all': 'All',
  'wall.soon': 'The guestbook opens soon.',
  'wall.none': 'No words yet. Live one life and leave the first.',
  'support.kakaopay': 'Send a latte',
  'support.toss': 'Support with Toss',
  'support.qrAlt': 'KakaoPay transfer QR code',
  'support.linkedin': 'The maker’s LinkedIn',
  'support.intro': 'The world is a mess, and I don’t know what tomorrow brings. Still, I’m a designer who makes this and that. For the record, I really, really love iced lattes.',
});

registerPlaceText('en', {
  villaParking: { area: 'Neighborhood', name: 'Villa parking lot' },
  aptGarden: { area: 'Neighborhood', name: 'Apartment flowerbed' },
  recycling: { area: 'Neighborhood', name: 'Recycling corner' },
  villaAlley: { area: 'Neighborhood', name: 'Villa alley' },
  entrance: { area: 'Neighborhood', name: 'Front hallway' },
  living: { area: 'Neighborhood', name: 'Living room' },
  kitchen: { area: 'Neighborhood', name: 'Home kitchen' },
  restaurant: { area: 'Downtown', name: 'Restaurant kitchen' },
  foodAlley: { area: 'Downtown', name: 'Back alley of restaurants' },
  convenience: { area: 'Downtown', name: 'Outside the convenience store' },
  park: { area: 'Park', name: 'Neighborhood park' },
  catHillAlley: { area: 'Neighborhood', name: 'Hillside alley' },
  catRooftop: { area: 'Neighborhood', name: 'Rooftop' },
  catRedevelop: { area: 'Neighborhood', name: 'Alley being emptied' },
  catEmptyRoom: { area: 'Neighborhood', name: 'Empty house' },
  catDemolition: { area: 'Neighborhood', name: 'Demolition site' },
  catSiteFence: { area: 'Neighborhood', name: 'Construction fence' },
  cockroachBunsik: { area: 'Downtown', name: 'Snack bar kitchen' },
  dogRedevelop: { area: 'Neighborhood', name: 'Redevelopment alley' },
  dogJunkyard: { area: 'Downtown', name: 'Scrapyard' },
  flyJunkyard: { area: 'Neighborhood', name: 'Scrapyard' },
  mosquitoBasin: { area: 'Neighborhood', name: 'Red tub by the guard booth' },
  mosquitoBooth: { area: 'Neighborhood', name: 'Apartment guard booth' },
  mosquitoBasement: { area: 'Neighborhood', name: 'Underground parking' },
  mouseBanjiha: { area: 'Neighborhood', name: 'Semi-basement room' },
  pigeonStation: { area: 'Downtown', name: 'Subway exit square' },
  pigeonOverpass: { area: 'Downtown', name: 'Under the overpass' },
  pigeonSubway: { area: 'Downtown', name: 'On the subway' },
  sparrowShops: { area: 'Neighborhood', name: 'Shop street' },
});

/* 정적 HTML 문구: data-i18n(글자), data-i18n-html(줄바꿈 포함), data-i18n-aria(aria-label) */
function applyStaticText() {
  document.querySelectorAll('[data-i18n]').forEach((el) => { el.textContent = tx(el.dataset.i18n); });
  document.querySelectorAll('[data-i18n-html]').forEach((el) => {
    // 번역 문구는 우리가 쓴 고정 문자열이고 <br>만 쓴다. 다른 태그는 글자로 보이게 막는다
    el.replaceChildren(...tx(el.dataset.i18nHtml).split('<br>').flatMap((part, i) => (i ? [document.createElement('br'), part] : [part])));
  });
  document.querySelectorAll('[data-i18n-aria]').forEach((el) => el.setAttribute('aria-label', tx(el.dataset.i18nAria)));
}

/** 영어 문장 속 동물 이름은 소문자로 ("a stray cat") */
const nameInText = (sp) => (LANG === 'en' ? sp.name.toLowerCase() : sp.name);
